services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: plataforma-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - plataforma-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  rabbitmq_data:

networks:
  plataforma-network:
    name: "plataforma-network"
    external: true
