apiVersion: v1
kind: Secret
metadata:
  name: auth-api-secret
  namespace: plataforma-educacional
type: Opaque
data:
  JWT__Key: ZWR1Y2Etc2VjcmV0           # base64("educa-secret")
  ConnectionStrings__Default: U2VydmVyPXNxbHNlcnZlciwxNDMzO0RhdGFiYXNlPUF1dGhEQjtVc2VyIElkPXNhO1Bhc3N3b3JkPVlvdXJTdHJvbmchUGFzc3cwZDtUcnVzdFNlcnZlckNlcnRpZmljYXRlPVRydWU7
  # base64("Server=sqlserver,1433;Database=AuthDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;")
