apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-api-config
  namespace: plataforma-educacional
data:
  ASPNETCORE_ENVIRONMENT:        "Kubernetes"
  ApiSettings__AuthApiUrl:       "http://auth-api:8081"
  ApiSettings__ConteudoApiUrl:   "http://conteudo-api:8082"
  ApiSettings__AlunosApiUrl:     "http://alunos-api:8083"
  ApiSettings__PagamentosApiUrl: "http://pagamentos-api:8084"
