apiVersion: v1
kind: Secret
metadata:
  name: conteudo-api-secret
  namespace: plataforma-educacional
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ConteudoDB;User Id=sa;Password=PlataformaEducacional123!;TrustServerCertificate=true;Encrypt=True;Application Name=Conteudo.API;"
  JwtSettings__SecretKey: "plataforma-educacional-JWT-Key_89097151-de66-4f98-9974-5485b810c9ed"
