services:
  alunos-api:
    image: educa/alunos-api:latest
    container_name: plataforma-alunos-api
    build:
      context: ../../src/backend
      dockerfile: alunos-api/Dockerfile
    ports:
      - "5003:5003"
      - "7003:7003"
    expose:
      - 5003
      - 7003
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5003;http://+:7003
      - ASPNETCORE_Kestrel__Certificates__Default__Password=PlataformaEducacional123!
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AlunosDB;User Id=sa;Password=PlataformaEducacional123!;TrustServerCertificate=True;
      - JwtSettings__SecretKey=PlataformaEducacional123!SuperSecretKey2024@#$
      - JwtSettings__Issuer=PlataformaEducacional
      - JwtSettings__Audience=PlataformaEducacional
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin123
      - ExternalApis__ConteudoApi=http://conteudo-api:7002
    networks:
      - plataforma-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8082/health']
      interval: 15s
      timeout: 5s
      retries: 5

# volumes:
#   pagamentos-api-volume: 

networks:
  plataforma-network:
    name: "plataforma-network"
    external: true
