services:
  bff-api:
    image: educa/bff-api:latest
    container_name: plataforma-bff-api
    env_file:
      - ../../src/backend/.env
    build:
      context: ../../src/backend
      dockerfile: bff-api/Dockerfile
    ports:
      - "5000:5000"
      - "7000:7000"
    expose:
      - 5000
      - 7000
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5000;http://+:7000
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - RedisSettings__ConnectionString=redis:6379
      - ApiSettings__AuthApiUrl=http://auth-api:5001
      - ApiSettings__ConteudoApiUrl=http://conteudo-api:5002
      - ApiSettings__AlunosApiUrl=http://alunos-api:5003
      - ApiSettings__PagamentosApiUrl=http://pagamentos-api:5004
    networks:
      - plataforma-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/health']
      interval: 15s
      timeout: 5s
      retries: 5

# volumes:
#   pagamentos-api-volume: 

networks:
  plataforma-network:
    name: "plataforma-network"
    external: true
