services:
  conteudo-api:
    image: educa/conteudo-api:latest
    container_name: plataforma-conteudo-api
    env_file:
      - ../../src/backend/.env
    build:
      context: ../../src/backend
      dockerfile: conteudo-api/Dockerfile
    ports:
      - "5002:5002"
      - "7002:7002"
    expose:
      - 5002
      - 7002
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5002;http://+:7002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATES}
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ConteudoDB;User Id=sa;Password=${DB_PASSWORD_CONTEUDO};TrustServerCertificate=True;
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
    networks:
      - plataforma-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5002/health']
      interval: 15s
      timeout: 5s
      retries: 5

# volumes:
#   pagamentos-api-volume: 

networks:
  plataforma-network:
    name: "plataforma-network"
    external: true