services:
  auth-api:
    image: educa/auth-api:latest
    container_name: plataforma-auth-api
    env_file:
      - ../../src/backend/.env
    build:
      context: ../../src/backend
      dockerfile: auth-api/Dockerfile
    ports:
      - "5001:5001"
      - "7001:7001"
    expose:
      - 5001
      - 7001
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5001;http://+:7001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATES}
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AuthDB;User Id=sa;Password=${DB_PASSWORD_AUTH};TrustServerCertificate=True;
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__ExpiryMinutes=15
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
    networks:
      - plataforma-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5001/health']
      interval: 15s
      timeout: 5s
      retries: 5

# volumes:
#   pagamentos-api-volume: 

networks:
  plataforma-network:
    name: "plataforma-network"
    external: true