name: Auth-API - CI/CD

on:
  pull_request:
    branches: [ DEV, PR, main ]
    paths:
      - 'src/backend/auth-api/**'

  push:
    branches: [ DEV, PR, main ]
    paths:
      - 'src/backend/auth-api/**'

env:
  DOTNET_VERSION: '9.0.x'

jobs:

  # ===============================================
  # BUILD + TESTES DO MICROSSERVIÇO (CI RÁPIDO)
  # Rodado em:
  #   - PR → DEV, PR, main
  #   - Push → DEV, PR
  # ===============================================
  service-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configuração .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore do microsserviço Auth-API
        run: dotnet restore src/backend/auth-api/Auth.API.sln

      - name: Build do microsserviço Auth-API
        run: dotnet build src/backend/auth-api/Auth.API.sln --configuration Release --no-restore

      - name: Execução de Testes Unitários Auth-API
        run: dotnet test src/backend/tests/Auth.UnitTests/Auth.UnitTests.csproj --configuration Release

      - name: Execução de Testes Integrados Auth-API
        run: dotnet test src/backend/tests/Auth.IntegrationTests/Auth.IntegrationTests.csproj --configuration Release

  # ===============================================
  # TESTES COMPLETOS (APENAS MAIN = CI completo)
  # ===============================================
  full-tests:
    needs: service-tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Configuração .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Full da Solution MBA.Modulo5
        run: dotnet restore src/backend/MBA.Modulo5.sln

      - name: Execução de Testes do eco-sistema
        run: dotnet test src/backend/MBA.Modulo5.sln --configuration Release 

  # ===============================================
  # DEPLOY (DOCKER BUILD & PUSH)
  # Somente MAIN
  # ===============================================
  docker-build-push:
    needs: full-tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Identificando a Versão Deste Build
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" src/backend/auth-api/src/Auth.API/Auth.API.csproj)
          echo "version=$VERSION" >> $GITHUB_OUTPUT  

      - name: Credenciais do repositório Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Criação da imagem e Push no repositório do Docker Hub do microsserviço Auth-API
        uses: docker/build-push-action@v5
        with:
          context: src/backend
          file: src/backend/auth-api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/project5-auth-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/project5-auth-api:${{ steps.get_version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/project5-auth-api:${{ github.sha }}
