name: Frontend (Angular) - CI/CD

on:
  push:
    paths:
      - 'src/frontend/**'
  pull_request:
    paths:
      - 'src/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@v4

      # Instala Node
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Instala dependências
      - name: 📦 Install dependencies
        run: |
          cd src/frontend
          npm install

      # Build do Angular
      - name: 🏗 Build Angular project
        run: |
          cd src/frontend
          npm run build --if-present

  # ===========================
  # DOCKER BUILD & PUSH
  # ===========================
  docker-build-push:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@v4

      - name: 🔐 Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🐳 Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: src/frontend
          file: src/frontend/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/project5-frontend:latest
            ${{ vars.DOCKER_USERNAME }}/project5-frontend:${{ github.sha }}
