name: Pagamentos-API - CI/CD

on:
  pull_request:
    branches: [ DEV, main ]
    paths:
      - 'src/backend/pagamentos-api/**'
      - 'src/backend/building-blocks/**'

  push:
    branches: [ DEV, main ]
    paths:
      - 'src/backend/pagamentos-api/**'
      - 'src/backend/building-blocks/**'

concurrency:
  group: ${{github.workflow}}-${{github.ref}}

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  # ===============================================
  # Lint / Qualidade de código / Estruturas
  # ===============================================
  lint-validation:
    runs-on: ubuntu-latest

    steps:    
      - name: Realizando checkout
        uses: actions/checkout@v4

      - name: Execução antecipada do LINT para aferir qualidade de código
        run: dotnet format src/backend/pagamentos-api/Pagamentos.API.sln --verify-no-changes

  # ===============================================
  # BUILD + TESTES DO MICROSSERVIÇO (CI RÁPIDO)
  # Rodado em:
  #   - PR → DEV, main
  #   - Push → DEV
  # ===============================================
  api-tests:
    needs: lint-validation
    runs-on: ubuntu-latest

    steps:
      - name: Realizando checkout
        uses: actions/checkout@v4

      - name: Configuração .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: |
            src/backend/building-blocks/**/*.csproj
            src/backend/pagamentos-api/**/*.csproj
            src/backend/pagamentos-api/**/*.sln

      - name: Restore do microsserviço Pagamentos-API
        run: dotnet restore src/backend/pagamentos-api/Pagamentos.API.sln
                
      - name: Build do microsserviço Pagamentos-API
        run: dotnet build src/backend/pagamentos-api/Pagamentos.API.sln --configuration Release --no-restore

      - name: Restore da Solution para atender aos testes unitários e de integração
        run: dotnet restore src/backend/MBA.Modulo5.sln

      - name: Execução de Testes Unitários Pagamentos-API
        run: dotnet test src/backend/tests/Pagamentos.UnitTests/Pagamentos.UnitTests/Pagamentos.UnitTests.csproj --configuration Release --no-restore --logger trx --results-directory "Pagamentos-Unit-Tests-Results" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./

      - name: Gravação dos artefatos de testes integrados
        uses: actions/upload-artifact@v4
        with:
          name: pagamentos-unit-tests-results
          path: Pagamentos-Unit-Tests-Results

      - name: Execução de Testes Integrados Pagamentos-API
        run: dotnet test src/backend/tests/Pagamentos.IntegrationTests/Pagamentos.IntegrationTests/Pagamentos.IntegrationTests.csproj --configuration Release --no-restore --logger trx --results-directory "Pagamentos-Integration-Tests-Results" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./

      - name: Gravação dos artefatos de testes integrados
        uses: actions/upload-artifact@v4
        with:
          name: pagamentos-integration-tests-results
          path: Pagamentos-Integration-Tests-Results

  # ===============================================
  # TESTES COMPLETOS (APENAS MAIN = CI completo)
  # ===============================================
  solution-tests:
    needs: api-tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Realizando checkout
        uses: actions/checkout@v4

      - name: Configuração .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Full da Solution MBA.Modulo5
        run: dotnet restore src/backend/MBA.Modulo5.sln

      - name: Execução de Testes do eco-sistema
        run: dotnet test src/backend/MBA.Modulo5.sln --configuration Release --no-restore --logger trx --results-directory "Pagamentos-Solution-Tests-Results" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./

      - name: Gravação dos artefatos de testes da solução
        uses: actions/upload-artifact@v4
        with:
          name: pagamentos-solution-tests-results
          path: Pagamentos-Solution-Tests-Results

  # ===============================================
  # DEPLOY (DOCKER BUILD & PUSH)
  # Somente MAIN
  # ===============================================
  docker-build-push:
    needs: solution-tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Realizando checkout
        uses: actions/checkout@v4

      - name: Identificando a Versão Deste Build
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" src/backend/pagamentos-api/src/Pagamentos.API/Pagamentos.API.csproj)
          echo "version=$VERSION" >> $GITHUB_OUTPUT  

      - name: Credenciais do repositório Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configuração de Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Criação da imagem e Push no repositório do Docker Hub do microsserviço Pagamentos-API
        uses: docker/build-push-action@v5
        with:
          context: src/backend
          file: src/backend/pagamentos-api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/project5-pagamentos-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/project5-pagamentos-api:${{ steps.get_version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/project5-pagamentos-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max